export const HESH_CALLOUTS: string[] = [
  'Contact front!',
  'Enemy down!',
  'Logan, move up!',
  'Watch your six!',
  'Grenade out!',
  'Cover me!',
  'I\'m in position!',
  'They\'re flanking us!',
  'Suppressive fire!',
  'Multiple contacts!',
  'On your left!',
  'On your right!',
  'Squad, regroup!',
  'Don\'t let them through!',
  'Eyes up, they\'re in the containers!',
  'Taking fire from the warehouse!',
  'I\'ve got eyes on the target!',
  'Logan, on me!',
  'Push through, don\'t slow down!',
  'Hold this position!',
  'Enemy reinforcements incoming!',
  'Last man standing—finish it!',
  'Tango down!',
  'Clear!',
  'Sector clear!',
  'Ghost team, all clear.',
  'Reload while you can!',
  'Get to cover!',
  'They know we\'re here!',
  'How copy, Logan?',
  'We\'re almost through.',
  'Stay sharp.',
  'Keep moving, don\'t stop!',
  'That\'s what I\'m talking about!',
  'Nice shot!',
  'Sniper! Get down!',
  'Watch out for the high ground!',
  'Going loud.',
  'Breach and clear!',
  'Room clear!',
  'Logan, you good?',
  'The Federation won\'t give up easy.',
  'Stay frosty.',
  'Move it, Logan!',
  'We\'ve got their position!',
  'Confirm kill.',
  'Enemy squad neutralized.',
  'Sitrep: all clear.',
  'Ghost Six, objective secured.',
  'FUBAR... but we make it work.',
  'Dad would be proud.',
];

export function getHeshCallout(index?: number): string {
  if (index !== undefined) return HESH_CALLOUTS[index % HESH_CALLOUTS.length];
  return HESH_CALLOUTS[Math.floor(Math.random() * HESH_CALLOUTS.length)];
}
